
parseMe="""

INTERNET_OPTION_ALTER_IDENTITY 80

INTERNET_OPTION_ASYNC 30

INTERNET_OPTION_ASYNC_ID 15

INTERNET_OPTION_ASYNC_PRIORITY 16

INTERNET_OPTION_BYPASS_EDITED_ENTRY 64

INTERNET_OPTION_CACHE_STREAM_HANDLE 27

INTERNET_OPTION_CALLBACK 1

INTERNET_OPTION_CALLBACK_FILTER 54

INTERNET_OPTION_CLIENT_CERT_CONTEXT 84

INTERNET_OPTION_CODEPAGE 68

INTERNET_OPTION_CODEPAGE_PATH 100

INTERNET_OPTION_CODEPAGE_EXTRA 101

INTERNET_OPTION_COMPRESSED_CONTENT_LENGTH 147

INTERNET_OPTION_CONNECT_BACKOFF 4

INTERNET_OPTION_CONNECT_RETRIES 3

INTERNET_OPTION_CONNECT_TIME 55

INTERNET_OPTION_CONNECT_TIMEOUT 2

INTERNET_OPTION_CONNECTED_STATE 50

INTERNET_OPTION_CONTEXT_VALUE 45

INTERNET_OPTION_CONTROL_RECEIVE_TIMEOUT 6

INTERNET_OPTION_CONTROL_SEND_TIMEOUT 5

INTERNET_OPTION_DATA_RECEIVE_TIMEOUT 8

INTERNET_OPTION_DATA_SEND_TIMEOUT 7

INTERNET_OPTION_DATAFILE_EXT 96

INTERNET_OPTION_DIGEST_AUTH_UNLOAD 76

INTERNET_OPTION_DISABLE_AUTODIAL 70

INTERNET_OPTION_DISCONNECTED_TIMEOUT 49

INTERNET_OPTION_ENABLE_HTTP_PROTOCOL 148

INTERNET_OPTION_ENABLE_REDIRECT_CACHE_READ 122

INTERNET_OPTION_ENCODE_EXTRA 155

INTERNET_OPTION_END_BROWSER_SESSION 42

INTERNET_OPTION_ERROR_MASK 62

INTERNET_OPTION_ENTERPRISE_CONTEXT 159

INTERNET_OPTION_FROM_CACHE_TIMEOUT 63

INTERNET_OPTION_HSTS 157

INTERNET_OPTION_HTTP_DECODING 65

INTERNET_OPTION_HTTP_PROTOCOL_USED 149

INTERNET_OPTION_HTTP_VERSION 59

INTERNET_OPTION_IDENTITY 78

INTERNET_OPTION_IDLE_STATE 51

INTERNET_OPTION_IDN 102

INTERNET_OPTION_IGNORE_OFFLINE 77

INTERNET_OPTION_KEEP_CONNECTION 22

INTERNET_OPTION_LISTEN_TIMEOUT 11

INTERNET_OPTION_MAX_CONNS_PER_1_0_SERVER 74

INTERNET_OPTION_MAX_CONNS_PER_PROXY 103

INTERNET_OPTION_MAX_CONNS_PER_SERVER 73

INTERNET_OPTION_OFFLINE_MODE 26

INTERNET_OPTION_OFFLINE_SEMANTICS 52

INTERNET_OPTION_OPT_IN_WEAK_SIGNATURE 176

INTERNET_OPTION_PASSWORD 29

INTERNET_OPTION_PER_CONNECTION_OPTION 75

INTERNET_OPTION_POLICY 48

INTERNET_OPTION_PROXY 38

INTERNET_OPTION_PROXY_PASSWORD 44

INTERNET_OPTION_PROXY_SETTINGS_CHANGED 95

INTERNET_OPTION_PROXY_USERNAME 43

INTERNET_OPTION_READ_BUFFER_SIZE 12

INTERNET_OPTION_RECEIVE_THROUGHPUT 57

INTERNET_OPTION_RECEIVE_TIMEOUT 6

INTERNET_OPTION_REFRESH 37

INTERNET_OPTION_REMOVE_IDENTITY 79

INTERNET_OPTION_REQUEST_PRIORITY 58

INTERNET_OPTION_RESET_URLCACHE_SESSION 60

INTERNET_OPTION_SECONDARY_CACHE_KEY 53

INTERNET_OPTION_SEND_THROUGHPUT 56

INTERNET_OPTION_SEND_TIMEOUT 5

INTERNET_OPTION_SERVER_CERT_CHAIN_CONTEXT 105

INTERNET_OPTION_SETTINGS_CHANGED 39

INTERNET_OPTION_SUPPRESS_SERVER_AUTH 104

INTERNET_OPTION_USER_AGENT 41

INTERNET_OPTION_USERNAME 28

INTERNET_OPTION_WRITE_BUFFER_SIZE 13

"""







# PAGE_EXECUTE 0x10

# PAGE_EXECUTE_READ 0x20
# PAGE_EXECUTE_READWRITE 0x40
# PAGE_EXECUTE_WRITECOPY 0x80
# PAGE_NOACCESS 0x01

# PAGE_READONLY 0x02
# PAGE_READWRITE 0x04
# PAGE_WRITECOPY 0x08

# PAGE_TARGETS_INVALID 0x40000000

# PAGE_TARGETS_NO_UPDATE 0x40000000

# PAGE_GUARD 0x100

# PAGE_NOCACHE 0x200
# PAGE_WRITECOMBINE 0x400



# out = out.replace(red, "")	

###replace the parseMe!!!!!


parseMe2=parseMe.replace("=","")
# print (parsMe3)
parsMe3 = parseMe2.split("\n")

lookUp={}
reverseLookUp={}
for each in parsMe3:
	try:
		each2=each.split(" ")
		valStr=each2[0]
		try:
			hexV=each2[2]
		except:

			hexV=each2[1]
		lookUp[valStr]=hexV
		reverseLookUp[int(hexV,16)]=valStr
	except:
		print ("except", each)
		pass


word_type="mem"  ### change this

print (word_type+"_LookUp =", lookUp)
print (word_type+"_ReverseLookUp =",reverseLookUp)